 version: "3"
 services:
  influxdb:
    image: influxdb:latest
    container_name: "influxdb"
    ports:
      - "8086:8086"
      - "8090:8090"
      - "8088:8088"
      - "8083:8083"
    environment:
      - INFLUXDB_REPORTING_DISABLED=false
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_BIND_ADDRESS=:8088
      - INFLUXDB_ADMIN_ENABLED=true
      - PRE_CREATE_DB=cadvisor
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - /srv/docker/influxdb/data:/var/lib/influxdb
  grafana:
    user: root
    image: grafana/grafana
    container_name: "grafana"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/setup.sh:/setup.sh
    entrypoint: /setup.sh
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    links:
      - influxdb
      - prometheus
    depends_on:
      - influxdb
      - prometheus
  prometheus:
    image: prom/prometheus
    container_name: "prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml